services:
  web-app:
    image: ghcr.io/billetera-seca-2025/billetera-seca-web-app:latest
    ports:
      - "3000:3000"
    networks:
      - billetera-seca-network
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    deploy: {}  # opcional
    mem_limit: 256m
    cpus: 0.5

  fake-api:
    image: ghcr.io/billetera-seca-2025/fake-api:latest
    ports:
      - "8081:8081"
    networks:
      - billetera-seca-network
    mem_limit: 128m
    cpus: 0.3

  api:
    image: ghcr.io/billetera-seca-2025/billetera-seca-dev:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - api-db
    networks:
      - billetera-seca-network
    mem_limit: 512m
    cpus: 1.0

  api-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - api-db-data:/var/lib/postgresql/data
    networks:
      - billetera-seca-network
    mem_limit: 512m
    cpus: 0.8
